services:
  - docker

branches:
  only:
  - master

env:
  - IMAGE_NAME=base-notebook

script:
  - docker build --no-cache -t kevinprotoss/$IMAGE_NAME:latest .

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script: docker push "kevinprotoss/$IMAGE_NAME"
  on:
    branch: master

notifications:
  on_success: change
  on_failure: always
  on_start: never
